#!/usr/bin/env python
"""extract-snippets, pull the ``# region``-marked blocks out of the type-checked example files into

- ``examples/snippets.json``, which the docs render by id, and
- ``src/actrone_memory/_example_snippets.py``, which the ``actrone-memory add`` recipes are
  built from,

so every snippet a user sees, on the site or from the CLI, is real, mypy-checked code from the
current library: an example that stops type-checking fails CI before it can be published stale.

Markers::

    # region <id>
...code...
    # endregion <id>

``--check`` verifies both outputs are in sync with the sources (CI gate) instead of writing them.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"
OUT = EXAMPLES_DIR / "snippets.json"
OUT_PY = EXAMPLES_DIR.parent / "src" / "actrone_memory" / "_example_snippets.py"

REGION = re.compile(r"#\s*region\s+(\S+)\s*\n(.*?)\n\s*#\s*endregion", re.DOTALL)

MODULE_HEADER = '''"""GENERATED by scripts/extract_snippets.py from the mypy-checked examples.

Do not edit: change the example, then run ``python scripts/extract_snippets.py``.
"""

# ruff: noqa: E501

from __future__ import annotations

from typing import Final

EXAMPLE_SNIPPETS: Final[dict[str, str]] = {
'''


def extract() -> dict[str, str]:
    snippets: dict[str, str] = {}
    # Top-level examples, the per-framework recipe sources under examples/frameworks/ (mirrors the
    # TS examples/frameworks/ pattern) and the use-case pages' sources under examples/use_cases/:
    # each # region block becomes a doc snippet.
    top_level = sorted(EXAMPLES_DIR.glob("*.py"))
    sources = (
        top_level
        + sorted((EXAMPLES_DIR / "frameworks").glob("*.py"))
        + sorted((EXAMPLES_DIR / "use_cases").glob("*.py"))
    )
    for path in sources:
        for match in REGION.finditer(path.read_text(encoding="utf-8")):
            snippet_id, body = match.group(1), match.group(2)
            if snippet_id in snippets:
                raise SystemExit(f"duplicate snippet id {snippet_id!r} (in {path.name})")
            snippets[snippet_id] = body.rstrip() + "\n"
    return snippets


def render_module(snippets: dict[str, str]) -> str:
    """Return the generated Python module the CLI recipes import.

    The use-case examples exist for the website's use-case pages only: they stay in snippets.json,
    which the site reads, and out of this module, which ships in the wheel for the CLI.
    """
    shipped = {key: value for key, value in snippets.items() if "-use-case-" not in key}
    entries = "".join(f"    {key!r}: {value!r},\n" for key, value in shipped.items())
    return MODULE_HEADER + entries + "}\n"


def _current(path: Path) -> str:
    """Read a file for comparison with CRLF normalised, so the gate is line-ending neutral."""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else ""


def main() -> None:
    snippets = extract()
    if not snippets:
        raise SystemExit("[extract-snippets] no # region snippets found under examples/")
    serialized = json.dumps(snippets, indent=2, ensure_ascii=False) + "\n"
    module = render_module(snippets)
    ids = ", ".join(snippets)

    if "--check" in sys.argv:
        outputs = (
            (OUT, serialized, "examples/snippets.json"),
            (OUT_PY, module, "src/actrone_memory/_example_snippets.py"),
        )
        stale = [name for path, expected, name in outputs if _current(path) != expected]
        if stale:
            raise SystemExit(
                f"[extract-snippets] DRIFT: {', '.join(stale)} stale. "
                "Run `python scripts/extract_snippets.py` and commit."
            )
        print(f"[extract-snippets] both outputs in sync ({len(snippets)}: {ids}) ok")
    else:
        OUT.write_text(serialized, encoding="utf-8", newline="\n")
        OUT_PY.write_text(module, encoding="utf-8", newline="\n")
        print(f"[extract-snippets] wrote {len(snippets)} snippet(s) ({ids})")


if __name__ == "__main__":
    main()
